export const SECTION_TITLES = {
  OVERVIEW: 'OverView',
  TECHNOLOGY: 'Technology',
  MAIN_PROBLEM: 'Main Problem',
  PROJECT: 'Project',
  KEY_EXPERIENCE: 'Key Experience',
} as const

export const projectsData = [
  {
    id: 1,
    title: 'イーデス(SEO)',
    slug: 'edesu',
    image: '/projects/edesu.png',
    name: 'Ateam-LifeDesign',
    projectUrl: 'https://www.a-tm.co.jp/top/',
    overviewText: [
      '『暮らしの「まよい」を「よかった」に。』を理念メッセージとして、複数の金融系Webメディア（アフィリエイト - SEO/PPC）のフロントエンド開発・Webデザイン・UI/UX / CVR改善・ブランド構築と反映・リプレイス・保守/運用などを担当してきました。',
    ],
    technologyText: ['xxx'],
    mainProblemText: ['xxx'],
    projectText: ['xxx'],
    keyExperienceText: ['xxx'],
  },
  {
    id: 2,
    title: 'ナビナビキャッシング(SEO)',
    slug: 'navinavi-seo',
    image: '/projects/navinavi_seo.png',
    name: 'Ateam-LifeDesign',
    projectUrl: 'https://a-cashing.com/',
    overviewText: [
      '「将来のお金の不安を解消するための金融知識・情報を提供する」をメッセージとしたナビナビブランド内の、キャッシング比較・情報メディア（SEOアフィリエイト）。',
    ],
    technologyText: ['xxx'],
    mainProblemText: ['xxx'],
    projectText: ['xxx'],
    keyExperienceText: ['xxx'],
  },
  {
    id: 3,
    title: 'ナビナビキャッシング(PPC)',
    slug: 'navinavi-ppc',
    image: '/projects/navinavi_ppc.png',
    name: 'Ateam-LifeDesign',
    projectUrl: 'https://a-cashing.com/cardloan/pc/aypl0001/y_listing/top/',
    overviewText: [
      '「将来のお金の不安を解消するための金融知識・情報を提供する」をメッセージとしたナビナビブランド内の、キャッシング比較サイト（PPCアフィリエイト）。',
    ],
    technologyText: ['xxx'],
    mainProblemText: ['xxx'],
    projectText: ['xxx'],
    keyExperienceText: ['xxx'],
  },
  {
    id: 4,
    title: 'お金借りる？(SEO)',
    slug: 'karireru',
    image: '/projects/okane_kariru.png',
    name: 'W-ENDLESS',
    projectUrl: 'https://www.karireru.com/',
    overviewText: [
      '消費者金融の利用者からの口コミ・審査データを元に、最適な商品を探せるカードローン比較メディア（SEOアフィリエイト）。',
    ],
    technologyText: ['xxx'],
    mainProblemText: ['xxx'],
    projectText: ['xxx'],
    keyExperienceText: ['xxx'],
  },
  {
    id: 5,
    title: 'JRおでかけネット',
    slug: 'odekake-net',
    image: '/projects/odekake_net.png',
    name: 'Root-Sea',
    projectUrl: 'https://www.jr-odekake.net/',
    overviewText: [
      'Root-Sea社が運営していた、旅客鉄道会社の観光情報サイトの「JRおでかけネット」。<br/>北陸・近畿・中国地方の大部分を営業エリアとするJR西日本の、それぞれの地域の観光情報や列車時間などの情報を提供するポータルサイト。',
      'Web事業部 の Webデザイナー として所属。<br/>PV数の獲得・改善 を目的とし、毎月のキャンペーン施策を元に、新規コンテンツ制作、Webサイト制作・保守運用（デザインからコーディングまで）、メルマガ制作 などを一貫して担当しました。<br/>また、クライアント案件として、新規のWebサイト制作なども担当。',
    ],
    technologyText: [
      'Wordpress / jQuery / Git / Gulp / HTML / CSS / Sass / JavaScript',
      'Photoshop / Illustrator',
    ],
    mainProblemText: [
      'ポータルサイトのPV数の獲得・改善',
      '新規クライアントの利益向上を目的とした新規Webサイト制作',
    ],
    projectText: [
      'キャンペーン施策に基づく、新規コンテンツ制作',
      'レギュレーションに沿った大手鉄道会社のポータルサイト制作・更新業務',
      'メルマガ運用',
      '新規クライアントのWebサイト制作',
    ],
    keyExperienceText: [
      '大手クライアント特有のデザイン・コーディングルールを考慮しながらの、大規模サイトの改修・新規コンテンツ制作',
      '制作会社の中でのルールや仕組み化',
      'ユーザー目線に沿った情報の本質が伝わりやすいコンテンツ制作',
      '新規クライアントのWebサイト制作',
      'Gulp などのタスクランナーによるコーディングの仕組み化・自動化・効率化',
      'コンポーネント思考によるUIパーツの管理方法',
    ],
  },
  {
    id: 6,
    title: '医療ワーカー',
    slug: 'iryo-worker',
    image: '/projects/iryo_worker.png',
    name: 'Media-Made',
    projectUrl: 'http://iryouworker.com/',
    overviewText: [
      'Media-Made社が運営していた、「医療・看護職」を専門とした求人・転職サイト。<br/>求職者 と 求人企業 をマッチングさせるためのオンラインプラットフォームであり、看護師・准看護師・助産師・保健師など をメインに取り扱う（※現在は「看護師ワーカー」に名称変更されている様子）。',
      'Web事業部 の Webデザイナー として所属。<br/>営業や求職者からの要望を元に、サイト改善施策をディレクターやプログラマーと打ち合わせし、CVR改善の目的で施策の遂行（デザインからコーディングまで）を一貫して担当しました。<br/>また、施策によってはディレクターとして社内ディレクションを担当。',
    ],
    technologyText: [
      'Wordpress / CakePHP / jQuery /  HTML / CSS / Sass / JavaScript / Git / Subversion',
      'Photoshop / Illustrator / Fireworks',
    ],
    mainProblemText: [
      'サイトのCVR改善',
      'UXの向上',
      '自社コーポレートサイトの制作',
    ],
    projectText: [
      '課題の改善を目的として、サイトの改善施策（ページ内の動線改善、見辛いコンテンツのUI/UX改善 や 画像の最適化など）を担当。',
      '自社の社員採用を目的とした採用サイトを、Wordpressで一貫して制作（※現在はサイト閉鎖）。',
      'その他、サイトの保守・運用業務など',
    ],
    keyExperienceText: [
      '社会人・Webデザイナーとしての基礎',
      'ざまざまな役割の経験（デザイナー・コーダー・社内ディレクション）',
      'ユーザー（求職者・営業職）にとって使いやすいサイトにするための、制作ノウハウ',
      '成果や効率性 を重視したコンテンツ・デザイン制作',
      'Gitによる複数人でのチーム開発',
      '医療系サービス特有のドメイン知識 の獲得',
    ],
  },
]
