export const projectsData = [
  {
    id: 1,
    title: 'イーデス(SEO)',
    slug: 'edesu',
    image: '/projects/edesu.png',
    text: '『暮らしの「まよい」を「よかった」に。』を理念メッセージとして、複数の金融系Webメディア（アフィリエイト - SEO/PPC）のフロントエンド開発・Webデザイン・UI/UX / CVR改善・ブランド構築と反映・リプレイス・保守/運用などを担当してきました。',
    projectUrl: 'https://www.a-tm.co.jp/top/',
  },
  {
    id: 2,
    title: 'ナビナビキャッシング(SEO)',
    slug: 'navinavi-seo',
    image: '/projects/navinavi_seo.png',
    text: '「将来のお金の不安を解消するための金融知識・情報を提供する」をメッセージとしたナビナビブランド内の、キャッシング比較・情報メディア（SEOアフィリエイト）。',
    name: 'Ateam-LifeDesign',
    projectUrl: 'https://a-cashing.com/',
  },
  {
    id: 3,
    title: 'ナビナビキャッシング(PPC)',
    slug: 'navinavi-ppc',
    image: '/projects/navinavi_ppc.png',
    text: '「将来のお金の不安を解消するための金融知識・情報を提供する」をメッセージとしたナビナビブランド内の、キャッシング比較サイト（PPCアフィリエイト）。',
    name: 'Ateam-LifeDesign',
    projectUrl: 'https://a-cashing.com/cardloan/pc/aypl0001/y_listing/top/',
  },
  {
    id: 4,
    title: 'お金借りる？(SEO)',
    slug: 'karireru',
    image: '/projects/okane_kariru.png',
    text: '消費者金融の利用者からの口コミ・審査データを元に、最適な商品を探せるカードローン比較メディア（SEOアフィリエイト）。',
    name: 'W-ENDLESS',
    projectUrl: 'https://www.karireru.com/',
  },
  {
    id: 5,
    title: 'JRおでかけネット',
    slug: 'odekake-net',
    image: '/projects/odekake_net.png',
    text: '北陸・近畿・中国地方の大部分を営業エリアとする旅客鉄道会社「JR西日本」が運営する観光情報サイト。',
    name: 'Root-Sea',
    projectUrl: 'https://www.jr-odekake.net/',
  },
  {
    id: 6,
    title: '医療ワーカー',
    slug: 'iryo-worker',
    image: '/projects/iryo_worker.png',
    text: '看護師・准看護師・助産師・保健師などを取り扱っている、「医療・看護職」を専門とした求人・転職サイト。',
    name: 'Media-Made',
    projectUrl: 'http://iryouworker.com/',
  },
]
