import profile from '@public/shared/profile.png'

export const data = [
  {
    _id: '1',
    name: 'Ateam-LifeDesign',
    jobTitle: 'Web Designer / Frontend Developer / Web Director',
    startDate: '2019-10',
    endDate: null,
    description: [
      '概要： 複数の金融系Webメディア（アフィリエイト - SEO / PPC）のフロントエンド開発・Webデザイン・UI/UX / CVR改善・デザインシステム導入・ブランド構築とプロダクトへの反映・CSSリプレイス・保守/運用 などを担当。',
      '仕事を通じて、Next.js・React・TypeScript・TailwindCSS・Storybook・VRTなど、さまざまな モダンフロントエンド技術を経験しました。',
      'また、デザイナー職能の中でのフロントエンド開発メンバーのリーダー担当を経験し、小規模のチームの管理・リードしました。',
      '技術スタック： Next.js / React / TypeScript / JavaScript / TailwindCSS / CSS Modules / Emotion / HTML / CSS / Sass / Storybook / VRT / Jest',
      '周辺ツール： Docker / Git / GitLab / Google Analytics / Google Search Console',
      'デザインツール： Figma / Photoshop / Illustrator / XD',
    ],
    url: 'https://life-design.a-tm.co.jp/',
    logo: profile,
  },
  {
    _id: '2',
    name: 'W-ENDLESS',
    jobTitle: 'Web Designer / Frontend Developer / Web Director',
    startDate: '2019-01',
    endDate: '2019-09',
    description: [
      '概要： 複数のWebメディア（アフィリエイト - SEO）のWeb制作（企画・UI/UX改善・フロントエンド開発・サイト表示速度改善・SEO改善まで）を担当。',
      '金融・美容 商材のWebメディアのCVR向上を目的とし、解析データに基づきチーム内で決定した施策として、新規コンテンツ作成・既存コンテンツ改善、サイト表示速度改善などを担当しました。',
      '全体として、アフィリエイトのビジネスモデルの理解や、PDCAのスピードの速い環境での仕事を経験することができました。',
      '技術スタック： HTML / CSS / Sass / JavaScript / jQuery / PHP / SQL',
      '周辺ツール： Wordpress / Git / AWS / Google Analytics / Google Search Console',
      'デザインツール： Photoshop / Illustrator',
    ],
    url: 'https://www.w-endless.co.jp/',
    logo: profile,
  },
  {
    _id: '3',
    name: 'Root-Sea',
    jobTitle: 'Web Designer / Web Director',
    startDate: '2017-01',
    endDate: '2019-01',
    description: [
      '概要： 大手鉄道会社のポータルサイトにて、キャンペーン毎のLP制作やレギュレーションに則った制作（デザインからコーディングまで）を担当。',
      '具体的には、キャンペーン施策に基づく新規コンテンツ制作、メルマガの運用や、新規クライアントのWebサイト制作など。',
      '全体として、制作会社の中でのルールや仕組み化などを考慮した仕事を経験することができました。',
      '技術スタック： HTML / CSS / Sass / JavaScript / jQuery',
      '周辺ツール： Wordpress / Git / Gulp',
      'デザインツール： Photoshop / Illustrator',
    ],
    url: 'https://example.com/company-b',
    logo: profile,
  },
  {
    _id: '4',
    name: 'Media-Made',
    jobTitle: 'Web Designer / Web Director',
    startDate: '2014-10',
    endDate: '2017-01',
    description: [
      '概要： Webデザイナー / コーダー / ディレクター兼務で、複数の医療系求人サイトのWeb制作（社内ディレクション・企画・デザイン・コーディングまで）を担当。',
      '具体的には、施策に基づく新規コンテンツ制作や、採用サイトの制作など。',
      '全体として、Web制作の流れ（ディレクション/デザイン/コーディング）や、他職能との連携などを経験することができました。',
      '技術スタック： HTML / CSS / Sass / JavaScript / jQuery / PHP',
      '周辺ツール： Wordpress / Git / Subversion',
      'デザインツール： Photoshop / Illustrator / Fireworks',
    ],
    url: 'https://example.com/company-b',
    logo: profile,
  },
]
