export const data = [
  { text: 'Next.js' },
  { text: 'React' },
  { text: 'TypeScript' },
  { text: 'HTML' },
  { text: 'CSS' },
  { text: 'JavaScript' },
  { text: 'jQuery' },
  { text: 'Tailwind CSS' },
  { text: 'Emotion' },
  { text: 'CSS Modules' },
  { text: 'Sass' },
  { text: 'Storybook' },
  { text: 'VRT (UI Test)' },
  { text: 'Jest' },
  { text: 'Git' },
  { text: 'Docker' },
  { text: 'Wordpress' },
  { text: 'PHP' },
  { text: 'SQL' },
  { text: 'Figma' },
  { text: 'Illustrator' },
  { text: 'Photoshop' },
  { text: 'LPO' },
  { text: 'CRO' },
  { text: 'SEO' },
]
