import { Inter } from 'next/font/google'

import { Footer } from '@components/Footer'
import { Navbar } from '@components/Navbar'
import { Providers } from '@components/providers'

import type { Metadata } from 'next'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={`${inter.className} bg-white text-zinc-700 dark:bg-zinc-900 dark:text-white`}
      >
        <Providers>
          <Navbar />

          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
